name: Download Monitor Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update submodules
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive

      - name: Install dependencies
        run: npm run composer:install

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: Release ${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: false

      - name: Download Monitor Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: download-monitor
          VERSION: ${{ steps.package-version.outputs.current-version }}
